project_id = "gp-d38b4843-211c-4bf1-bf32-d61ca25771e6"
org_id = "6a937d2be959543a010e9909"
name = "guavahack"
call_direction = "inbound"
base_image = "python-sandbox:3.12"
phone_number = "+14847408902"
tier = "guava-seed"
replicas = 1
enable_healthcheck = true
